import { IsString, IsOptional, MaxLength, IsEnum } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { GeneratedWebsiteStatus } from '@prisma/client';

export class SaveGeneratedWebsiteDto {
  @ApiPropertyOptional({
    description: 'Raw HTML content generated by DeepSeek',
    example: '<!DOCTYPE html><html><head>...</head><body><h1>Welcome</h1></body></html>',
  })
  @IsOptional()
  @IsString()
  @MaxLength(5000000, { message: 'HTML payload must not exceed 5MB' })
  html?: string;

  @ApiPropertyOptional({
    description: 'Raw CSS stylesheet content generated by DeepSeek',
    example: ':root { --primary: #FA8373; } body { font-family: sans-serif; }',
  })
  @IsOptional()
  @IsString()
  @MaxLength(5000000, { message: 'CSS payload must not exceed 5MB' })
  css?: string;

  @ApiPropertyOptional({
    description: 'Raw Vanilla JavaScript content generated by DeepSeek',
    example: 'document.addEventListener("DOMContentLoaded", () => { console.log("Init"); });',
  })
  @IsOptional()
  @IsString()
  @MaxLength(5000000, { message: 'JavaScript payload must not exceed 5MB' })
  javascript?: string;

  @ApiPropertyOptional({
    description: 'Status of the generated website workspace',
    enum: GeneratedWebsiteStatus,
    default: GeneratedWebsiteStatus.DRAFT,
  })
  @IsOptional()
  @IsEnum(GeneratedWebsiteStatus)
  status?: GeneratedWebsiteStatus;

  @ApiPropertyOptional({
    description: 'Custom slug for the website workspace',
    example: 'royal-moments-photography',
  })
  @IsOptional()
  @IsString()
  @MaxLength(80)
  slug?: string;

  @ApiPropertyOptional({
    description: 'Key-value mapping of placeholders to client asset URLs/references',
    example: { '{{LOGO_URL}}': 'data:image/png;base64,...', '{{IMAGE_1_URL}}': '...' },
  })
  @IsOptional()
  assetMappings?: Record<string, string>;
}

