import { TemplateConfig } from '../types';

export const emberHospitalityConfig: TemplateConfig = {
  id: 'ember-hospitality',
  componentKey: 'ember-hospitality',
  name: 'Ember Hospitality',
  slug: 'ember-hospitality',
  aliases: ['template-09-modern'],
  project: 'Project-1 (AI)',
  category: 'restaurant',
  designStyle: 'Luxury Editorial',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Boutique hotel, culinary experience, and fine hospitality template featuring rich crimson accents, dark atmospheric cards, and reservation forms.',
  thumbnailUrl: '/templates/ember-hospitality.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Hospitality', 'Hotel', 'Dining', 'Culinary', 'Crimson'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#991B1B',
    secondaryColor: '#D97706',
    accentColor: '#F59E0B',
    backgroundColor: '#0F0F12',
    textColor: '#F5F5F4',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Culinary Hero', description: 'Dining headline' },
    { key: 'about', name: 'Heritage Narrative', description: 'Culinary history' },
    { key: 'services', name: 'Dining Experiences', description: 'Menu & tasting' },
    { key: 'gallery', name: 'Atmosphere Gallery', description: 'Interior photos' },
    { key: 'testimonials', name: 'Guest Reviews', description: 'Guest feedback' },
    { key: 'contact', name: 'Table Reservation', description: 'Booking intake' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
