import { TemplateConfig } from '../types';

export const vitalisHealthConfig: TemplateConfig = {
  id: 'vitalis-health',
  componentKey: 'vitalis-health',
  name: 'Vitalis Health',
  slug: 'vitalis-health',
  aliases: ['template-06-modern'],
  project: 'Project-1 (AI)',
  category: 'healthcare',
  designStyle: 'Swiss Clean',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Modern healthcare and virtual telehealth portal template featuring a specialist search portal, quick action telehealth pills, interactive health metrics, and clinical teal palette.',
  thumbnailUrl: '/templates/vitalis-health.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Healthcare', 'Medical', 'Telehealth', 'Clinical', 'Teal'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#0D9488',
    secondaryColor: '#0284C7',
    accentColor: '#059669',
    backgroundColor: '#071311',
    textColor: '#E0F2FE',
    headingFont: 'Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Telehealth Portal', description: 'Specialist search hero' },
    { key: 'about', name: 'Clinical Overview', description: 'Care philosophy' },
    { key: 'services', name: 'Medical Specialties', description: 'Clinical services' },
    { key: 'gallery', name: 'Facility Showcase', description: 'Medical centers' },
    { key: 'testimonials', name: 'Patient Reviews', description: 'Patient feedback' },
    { key: 'contact', name: 'Appointment Intake', description: 'Booking & contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
