import { TemplateConfig } from '../types';

export const obsidianStudioConfig: TemplateConfig = {
  id: 'obsidian-studio',
  componentKey: 'obsidian-studio',
  name: 'Obsidian Studio',
  slug: 'obsidian-studio',
  aliases: ['template-02', 'project-1:template-02', 'template02'],
  project: 'Project-1 (AI)',
  category: 'creative',
  designStyle: 'Brutalist',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Dark creative agency & design studio template featuring oversized brutalist typography, asymmetric section grids, pitch-black backdrop, and Ochre highlights.',
  thumbnailUrl: '/templates/obsidian-studio.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Creative', 'Dark Agency', 'Oversized', 'Studio', 'Brutalist'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#E5B842',
    secondaryColor: '#FF3366',
    accentColor: '#F5C953',
    backgroundColor: '#0A0A0A',
    textColor: '#FFFFFF',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Hero Showcase', description: 'Oversized manifesto headline' },
    { key: 'about', name: 'Studio Narrative', description: 'Editorial story' },
    { key: 'services', name: 'Design Disciplines', description: 'Creative capabilities' },
    { key: 'gallery', name: 'Exhibition Spreads', description: 'Visual showcase' },
    { key: 'testimonials', name: 'Client Manifesto', description: 'Endorsements' },
    { key: 'contact', name: 'Studio Inquiry', description: 'Booking & contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
