import { TemplateConfig } from '../types';

export const terraEstateConfig: TemplateConfig = {
  id: 'terra-estate',
  componentKey: 'terra-estate',
  name: 'Terra Estate',
  slug: 'terra-estate',
  aliases: ['template-03-modern'],
  project: 'Project-1 (AI)',
  category: 'real-estate',
  designStyle: 'Luxury Editorial',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Luxury architecture and real estate template with warm terracotta/sand linen tones, full-bleed property sliders, specs pills, and inquiry forms.',
  thumbnailUrl: '/templates/terra-estate.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Real Estate', 'Luxury', 'Architecture', 'Property', 'Terracotta'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#B85B35',
    secondaryColor: '#D4C3B3',
    accentColor: '#8C3B1A',
    backgroundColor: '#F5EFE6',
    textColor: '#231B18',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Property Slider', description: 'Hero estate slider' },
    { key: 'about', name: 'Estate Overview', description: 'Architecture & features' },
    { key: 'services', name: 'Concierge Services', description: 'Real estate services' },
    { key: 'gallery', name: 'Property Gallery', description: 'Estate photos & media' },
    { key: 'testimonials', name: 'Client Reviews', description: 'Buyer feedback' },
    { key: 'contact', name: 'Private Inquiry', description: 'Inquiry form & contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
