import { WebsiteContent } from '@/api/content';

export const templateDefaultContents: Record<string, any> = {
  'aurora-corporate': {
    theme: {
      primaryColor: '#075C45',
      secondaryColor: '#C9A45C',
      accentColor: '#EAB308',
      backgroundColor: '#0F1412',
      textColor: '#F3F4F6',
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'spacious',
      containerWidth: 'wide',
      buttonSize: 'medium',
      designPreset: 'Executive Advisory',
      seoTitle: 'Aurora Corporate — Global Governance & Executive Advisory',
      seoDescription: 'Premier corporate consulting, capital restructuring, and risk assessment for Fortune 500 enterprises.',
      keywords: 'executive advisory, corporate governance, capital restructuring, risk management',
    },
    hero: {
      eyebrow: 'GLOBAL EXECUTIVE GOVERNANCE & STRATEGIC COUNSEL',
      title: 'Architecting Capital Resilience & Corporate Governance',
      description: 'Advising board chairs, family offices, and sovereign funds through complex cross-border restructuring, regulatory compliance, and risk optimization.',
      primaryButtonText: 'Initiate Mandate Consultation',
      primaryButtonUrl: '#contact',
      secondaryButtonText: 'Explore Practice Areas',
      secondaryButtonUrl: '#services',
    },
    about: {
      eyebrow: 'PARTNER GROUP PHILOSOPHY',
      title: 'Uncompromising Integrity Across Decades of Governance',
      description: 'Founded in Geneva in 1998, Aurora Corporate has overseen $45B+ in strategic transactions. Our partner group combines institutional rigor with discreet mandate execution.',
    },
    contact: {
      email: 'advisory@aurora-corporate.com',
      phone: '+1 (800) 450-8920',
      address: '100 Financial Center Blvd, Suite 4200, New York, NY 10005',
    },
  },

  'obsidian-studio': {
    theme: {
      primaryColor: '#E5B842',
      secondaryColor: '#FFFFFF',
      accentColor: '#A855F7',
      backgroundColor: '#0A0A0C',
      textColor: '#FFFFFF',
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'centered',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'luxury',
      containerWidth: 'standard',
      buttonSize: 'medium',
      designPreset: 'Creative Studio',
      seoTitle: 'Obsidian Studio — Brutalist Visual Architecture & Spatial Art',
      seoDescription: 'Radical simplicity and brutalist digital art direction for high-fashion brands and cultural institutions.',
      keywords: 'brutalist design, visual architecture, WebGL, high fashion digital',
    },
    hero: {
      eyebrow: 'BRUTALIST VISUAL ARCHITECTURE & EXPERIMENTAL DIGITAL',
      title: 'Monolithic Aesthetics Engineered for Cultural Impact',
      description: 'We reject generic web layout paradigms. Every commission is sculpted as a unique digital monument built on brutalist typography, spatial choreography, and 60fps WebGL execution.',
      primaryButtonText: 'View Exhibition Archives',
      primaryButtonUrl: '#gallery',
      secondaryButtonText: 'Initiate Commission Brief',
      secondaryButtonUrl: '#contact',
    },
    about: {
      eyebrow: 'STUDIO MANIFESTO',
      title: 'Radical Simplicity Meets Sculptural Technical Rigor',
      description: 'We operate at the intersection of high fashion, spatial digital installation, and custom-coded frontend architecture.',
    },
    contact: {
      email: 'commissions@obsidian-studio.com',
      phone: '+33 1 42 68 55 00',
      address: '74 Rue de Turenne, 75003 Paris, France',
    },
  },

  'terra-estate': {
    theme: {
      primaryColor: '#B85B35',
      secondaryColor: '#231B18',
      accentColor: '#D97706',
      backgroundColor: '#F5EFE6',
      textColor: '#231B18',
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'spacious',
      containerWidth: 'wide',
      buttonSize: 'large',
      designPreset: 'Luxury Editorial',
      seoTitle: 'Terra Estate — Architectural Sanctuaries & Prime Estates',
      seoDescription: 'Curated sanctuary residences engineered with organic terracotta, rammed earth, and coastal Malibu vistas.',
      keywords: 'luxury real estate, architectural homes, sanctuary residences, prime estates',
    },
    hero: {
      eyebrow: 'PRIVATE ESTATE COLLECTION & ARCHITECTURAL HOMES',
      title: 'Architectural Masterpieces in Prime Global Destinations',
      description: 'Curated sanctuary residences engineered with organic terracotta, rammed earth, floor-to-ceiling glass, and breathtaking natural vistas.',
      primaryButtonText: 'View Estate Catalog',
      primaryButtonUrl: '#services',
    },
    about: {
      eyebrow: 'ARCHITECTURAL HERITAGE',
      title: 'Organic Modernism Crafted in Earth & Glass',
      description: 'Every Terra estate is chosen for its harmonious integration with natural topography, private micro-climates, and sustainable thermal mass architecture.',
    },
    contact: {
      email: 'concierge@terra-estate.com',
      phone: '+1 (310) 555-TERRA',
      address: '22800 Pacific Coast Highway, Malibu, CA 90265',
    },
  },

  'nova-ai': {
    theme: {
      primaryColor: '#9333EA',
      secondaryColor: '#34D399',
      accentColor: '#38BDF8',
      backgroundColor: '#07080D',
      textColor: '#FFFFFF',
      headingFont: 'Inter, sans-serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'comfortable',
      containerWidth: 'wide',
      buttonSize: 'medium',
      designPreset: 'Modern Minimal',
      seoTitle: 'Nova AI — Autonomous Agentic Infrastructure & Sub-ms Vector Search',
      seoDescription: 'Enterprise AI orchestration engine with self-healing agentic loops and row-level encrypted vector search.',
      keywords: 'AI SaaS, agentic workflows, vector database, LLM fine-tuning, telemetry',
    },
    hero: {
      eyebrow: 'AUTONOMOUS MULTI-AGENT ORCHESTRATION & TELEMETRY',
      title: 'Next-Generation Neural Primitives for Enterprise AI',
      description: 'Deploy self-healing multi-agent workflows, sub-3ms vector search pipelines, and fine-tuned open-weights models on dedicated H100 GPU clusters.',
      primaryButtonText: 'Launch Terminal Demo',
      primaryButtonUrl: '#features',
    },
    about: {
      eyebrow: 'SYSTEM ARCHITECTURE',
      title: 'Zero-Trust Cyber Orchestration Layer',
      description: 'Nova AI delivers SOC2 Type II compliant agentic compute pipelines designed to process 100M+ daily embeddings with sub-millisecond p99 latency.',
    },
    contact: {
      email: 'api@nova-ai.io',
      phone: '+1 (888) 404-NOVA',
      address: '500 Howard Street, Suite 1200, San Francisco, CA 94105',
    },
  },

  'maison-atelier': {
    theme: {
      primaryColor: '#C5A059',
      secondaryColor: '#111111',
      accentColor: '#E2E8F0',
      backgroundColor: '#FAFAFA',
      textColor: '#111111',
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'centered',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'luxury',
      containerWidth: 'standard',
      buttonSize: 'medium',
      designPreset: 'Luxury Editorial',
      seoTitle: 'Maison Atelier — Haute Couture & Spatial Interior Direction',
      seoDescription: 'Bespoke haute couture gowns, private residence interior curation, and heirloom jewelry crafting in Paris.',
      keywords: 'haute couture, atelier, interior direction, luxury fashion, Paris',
    },
    hero: {
      eyebrow: 'HAUTE COUTURE & INTERIOR ATELIER // PARIS',
      title: 'Timeless Aesthetics & Spatial Artisanal Craftsmanship',
      description: 'Sculpting bespoke couture gowns, private residence interiors, and editorial art direction for discerning patrons across Paris, Milan, and New York.',
      primaryButtonText: 'Explore Atelier Lookbook',
      primaryButtonUrl: '#services',
    },
    about: {
      eyebrow: 'ATELIER HERITAGE',
      title: 'Artisanal Mastery Passed Through Generations',
      description: 'Each piece from Maison Atelier requires hundreds of hours of manual hand-draping, silk embroidery, and custom alabaster sculpting.',
    },
    contact: {
      email: 'contact@maison-atelier.fr',
      phone: '+33 1 53 05 90 00',
      address: '12 Place Vendôme, 75001 Paris, France',
    },
  },

  'vitalis-health': {
    theme: {
      primaryColor: '#0D9488',
      secondaryColor: '#E0F2FE',
      accentColor: '#38BDF8',
      backgroundColor: '#071311',
      textColor: '#E0F2FE',
      headingFont: 'Inter, sans-serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'comfortable',
      containerWidth: 'wide',
      buttonSize: 'medium',
      designPreset: 'Modern Minimal',
      seoTitle: 'Vitalis Health — Integrative Telehealth & Clinical Portal',
      seoDescription: 'Personalized medical care, 24/7 virtual specialist consultations, and continuous health monitoring.',
      keywords: 'telehealth, clinical portal, preventative cardiology, medical specialists, HIPAA care',
    },
    hero: {
      eyebrow: 'INTEGRATIVE TELEHEALTH & CLINICAL PORTAL',
      title: 'Personalized Medical Excellence & Precision Health Management',
      description: 'Connecting patients with board-certified clinical specialists, 24/7 telehealth consultations, and advanced diagnostic monitoring.',
      primaryButtonText: 'Book Appointment',
      primaryButtonUrl: '#contact',
    },
    about: {
      eyebrow: 'CLINICAL MISSION',
      title: 'Evidence-Based Preventative & Virtual Care',
      description: 'Vitalis Health integrates board-certified medical expertise with real-time biometric telemetry for proactive wellness and chronic care management.',
    },
    contact: {
      email: 'care@vitalis-health.com',
      phone: '+1 (800) 555-CARE',
      address: '750 Welch Road, Suite 310, Palo Alto, CA 94304',
    },
  },

  'horizon-finance': {
    theme: {
      primaryColor: '#1D4ED8',
      secondaryColor: '#0F172A',
      accentColor: '#3B82F6',
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      headingFont: 'Inter, sans-serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'spacious',
      containerWidth: 'wide',
      buttonSize: 'medium',
      designPreset: 'Executive Advisory',
      seoTitle: 'Horizon Finance — Wealth Management & Family Office Advisory',
      seoDescription: 'Institutional capital preservation, cross-border corporate structure, and high-yield capital allocation.',
      keywords: 'wealth management, family office, institutional capital, AUM advisory',
    },
    hero: {
      eyebrow: 'WEALTH MANAGEMENT & INSTITUTIONAL ADVISORY',
      title: 'Institutional Capital Preservation & Multi-Family Office Governance',
      description: 'Navigating global wealth preservation, cross-border corporate structure, and high-yield capital allocation for family offices and institutional endowments.',
      primaryButtonText: 'Explore Advisory Practices',
      primaryButtonUrl: '#services',
    },
    about: {
      eyebrow: 'INSTITUTIONAL HERITAGE',
      title: 'Disciplined Asset Stewardship Across Global Markets',
      description: 'Horizon Finance manages $12.5B+ in private assets with a focus on risk mitigation, tax-optimized estate structuring, and global private equity syndication.',
    },
    contact: {
      email: 'private@horizon-finance.com',
      phone: '+1 (212) 555-HORIZON',
      address: '200 Park Avenue, 45th Floor, New York, NY 10166',
    },
  },

  'framefolio': {
    theme: {
      primaryColor: '#FF3366',
      secondaryColor: '#E5E5E5',
      accentColor: '#A855F7',
      backgroundColor: '#0D0D0D',
      textColor: '#E5E5E5',
      headingFont: 'Inter, sans-serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'spacious',
      containerWidth: 'wide',
      buttonSize: 'large',
      designPreset: 'Creative Studio',
      seoTitle: 'Framefolio — Creative Design Studio & Brand Architecture',
      seoDescription: 'Brutalist design studio sculpting award-winning brand identities, physical exhibition graphics, and flagship digital platforms.',
      keywords: 'design studio, brand identity, brutalist portfolio, creative direction',
    },
    hero: {
      eyebrow: 'CREATIVE DESIGN STUDIO & BRAND ARCHITECTURE',
      title: 'Sculpting Bold Digital Artifacts & Iconic Visual Identities',
      description: 'We are a brutalist design studio crafting award-winning brand identities, physical exhibition graphics, and high-frequency digital platforms for visionary clients worldwide.',
      primaryButtonText: 'View Selected Work',
      primaryButtonUrl: '#projects',
    },
    about: {
      eyebrow: 'STUDIO ETHOS',
      title: 'High-Frequency Aesthetics Built to Outlast Trends',
      description: 'We combine stark kinetic typography with modular web engineering to create unforgettable digital flagships.',
    },
    contact: {
      email: 'studio@framefolio.design',
      phone: '+1 (800) 902-FRAME',
      address: '520 West 28th Street, New York, NY 10001',
    },
  },

  'ember-hospitality': {
    theme: {
      primaryColor: '#991B1B',
      secondaryColor: '#F5F5F4',
      accentColor: '#D97706',
      backgroundColor: '#0F0F12',
      textColor: '#F5F5F4',
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'luxury',
      containerWidth: 'wide',
      buttonSize: 'large',
      designPreset: 'Cinematic Hospitality',
      seoTitle: 'Ember Hospitality — Open-Fire Hearth Gastronomy & Villa Stays',
      seoDescription: 'Immerse in open-fire hearth gastronomy, sommelier-curated cellars, and atmospheric highland villa suites.',
      keywords: 'hospitality, wood fired hearth, Michelin partner, villa suites, luxury dining',
    },
    hero: {
      eyebrow: 'BOUTIQUE HOSPITALITY & WOOD-FIRED HEARTH',
      title: 'Artisanal Gastronomy & Atmospheric Luxury Stays',
      description: 'Immerse in open-fire hearth gastronomy, sommelier-curated cellars, and tranquil highland villa suites.',
      primaryButtonText: 'Reserve Table & Suite',
      primaryButtonUrl: '#contact',
    },
    about: {
      eyebrow: 'GASTRONOMIC HERITAGE',
      title: 'Open Hearth Cooking Rooted in Local Terroir',
      description: 'Our culinary salon features an 8-course wood-fired tasting menu paired with rare biodynamic vintages from our sommelier cellar.',
    },
    contact: {
      email: 'reservations@ember-hospitality.com',
      phone: '+1 (800) 450-EMBER',
      address: '1400 Highland Ridge Road, Aspen, CO 81611',
    },
  },

  'mono-architecture': {
    theme: {
      primaryColor: '#171717',
      secondaryColor: '#737373',
      accentColor: '#404040',
      backgroundColor: '#FFFFFF',
      textColor: '#171717',
      headingFont: 'Playfair Display, serif',
      bodyFont: 'Inter, sans-serif',
      heroLayout: 'split',
      aboutLayout: 'text-image',
      servicesStyle: 'cards',
      galleryStyle: 'grid',
      testimonialsStyle: 'cards',
      contactStyle: 'split',
      sectionSpacing: 'spacious',
      containerWidth: 'wide',
      buttonSize: 'medium',
      designPreset: 'Modern Minimal',
      seoTitle: 'Mono Architecture — Spatial & Monochromatic Practice',
      seoDescription: 'Minimalist reinforced concrete structures, cantilevered residences, and public spatial monuments defined by light and void.',
      keywords: 'architecture, raw concrete, minimalist spatial, cantilever, Copenhagen studio',
    },
    hero: {
      eyebrow: 'SPATIAL & ARCHITECTURAL PRACTICE // EST. 2014',
      title: 'Monochromatic Precision & Built Spatial Environments',
      description: 'Designing minimalist reinforced concrete structures, cantilevered residences, and public spatial monuments defined by light, shadow, and void.',
      primaryButtonText: 'View Built Archives',
      primaryButtonUrl: '#gallery',
    },
    about: {
      eyebrow: 'PRACTICE PHILOSOPHY',
      title: 'Spatial Geometry Stripped to Essential Void & Light',
      description: 'Mono Architecture crafts monolithic raw concrete structures in Copenhagen, Zurich, and Tokyo.',
    },
    contact: {
      email: 'inquiries@mono-architecture.dk',
      phone: '+45 33 12 40 00',
      address: 'Strandgade 44, 1401 Copenhagen, Denmark',
    },
  },
};
