import { TemplateConfig } from '../types';

export const solarisTechConfig: TemplateConfig = {
  id: 'solaris-tech',
  componentKey: 'solaris-tech',
  name: 'Solaris Quantum Energy',
  slug: 'solaris-tech',
  aliases: ['template-11-modern'],
  project: 'Project-2',
  category: 'technology',
  designStyle: 'Glassmorphism',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Solar energy & quantum clean-tech platform featuring amber glassmorphism grids, battery telemetry, and clean tech showcase.',
  thumbnailUrl: '/templates/solaris-tech.png',
  version: '1.0.0',
  author: 'Emperor Media Solution',
  tags: ['Clean Tech', 'Quantum Energy', 'Solar', 'Glassmorphism', 'SaaS'],
  isFeatured: true,
  status: 'ACTIVE',
  defaultTheme: {
    primaryColor: '#F59E0B',
    secondaryColor: '#10B981',
    accentColor: '#3B82F6',
    backgroundColor: '#060913',
    textColor: '#F3F4F6',
    headingFont: 'Outfit, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Quantum Energy Hero', description: 'Headline & telemetry' },
    { key: 'about', name: 'Solaris Architecture', description: 'Energy grid overview' },
    { key: 'services', name: 'Grid Solutions', description: 'Clean energy services' },
    { key: 'gallery', name: 'Solar Arrays', description: 'Visual installations' },
    { key: 'testimonials', name: 'Utility Feedback', description: 'Partner reviews' },
    { key: 'contact', name: 'Energy Audit Intake', description: 'Consultation request' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
