import { TemplateConfig } from '../types';

export const horizonFinanceConfig: TemplateConfig = {
  id: 'horizon-finance',
  componentKey: 'horizon-finance',
  name: 'Horizon Finance',
  slug: 'horizon-finance',
  aliases: ['template-07-modern'],
  project: 'Project-1 (AI)',
  category: 'consulting',
  designStyle: 'Swiss Clean',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Executive wealth management and private advisory template featuring structured data metrics, steel slate blue palette, and corporate card grids.',
  thumbnailUrl: '/templates/horizon-finance.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Finance', 'Wealth Management', 'Advisory', 'Banking', 'Corporate'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#1D4ED8',
    secondaryColor: '#0F172A',
    accentColor: '#3B82F6',
    backgroundColor: '#F8FAFC',
    textColor: '#0F172A',
    headingFont: 'Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Wealth Hero', description: 'Financial headline' },
    { key: 'about', name: 'Advisory Overview', description: 'Capital strategy' },
    { key: 'services', name: 'Financial Services', description: 'Practice areas' },
    { key: 'gallery', name: 'Case Studies', description: 'Deal flow showcase' },
    { key: 'testimonials', name: 'Investor Reviews', description: 'Client feedback' },
    { key: 'contact', name: 'Private Consultation', description: 'Contact details' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
