import { TemplateConfig } from '../types';

export const novaAiConfig: TemplateConfig = {
  id: 'nova-ai',
  componentKey: 'nova-ai',
  name: 'Nova AI',
  slug: 'nova-ai',
  aliases: ['template-04-modern'],
  project: 'Project-1 (AI)',
  category: 'saas',
  designStyle: 'Dark Futuristic',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Futuristic SaaS & AI command center template featuring cyber glow grids, tabbed CLI terminal HUD, sub-ms telemetry logs, and dark glowing accents.',
  thumbnailUrl: '/templates/nova-ai.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['SaaS', 'AI', 'Futuristic', 'Command Center', 'Cyber'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#9333EA',
    secondaryColor: '#34D399',
    accentColor: '#38BDF8',
    backgroundColor: '#07080D',
    textColor: '#FFFFFF',
    headingFont: 'Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'AI Command Hero', description: 'CLI Terminal & headline' },
    { key: 'about', name: 'Architecture Overview', description: 'Model capabilities' },
    { key: 'services', name: 'API Services', description: 'SDK & API features' },
    { key: 'gallery', name: 'Telemetry Dashboard', description: 'Visual metrics' },
    { key: 'testimonials', name: 'Developer Feedback', description: 'User reviews' },
    { key: 'contact', name: 'API Key Request', description: 'Developer contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
