import { TemplateConfig } from '../types';

export const framefolioConfig: TemplateConfig = {
  id: 'framefolio',
  componentKey: 'framefolio',
  name: 'Framefolio',
  slug: 'framefolio',
  aliases: ['template-08-modern'],
  project: 'Project-1 (AI)',
  category: 'portfolio',
  designStyle: 'Brutalist',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Creative design studio and portfolio template featuring asymmetric brutalist grids, project-focused gallery spreads, and bold typography.',
  thumbnailUrl: '/templates/framefolio.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Portfolio', 'Design Studio', 'Creative', 'Grid', 'Brutalist'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#FF3366',
    secondaryColor: '#0D0D0D',
    accentColor: '#E5E5E5',
    backgroundColor: '#0D0D0D',
    textColor: '#E5E5E5',
    headingFont: 'Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Portfolio Hero', description: 'Studio headline' },
    { key: 'about', name: 'Studio Ethos', description: 'Design approach' },
    { key: 'services', name: 'Design Disciplines', description: 'Services' },
    { key: 'gallery', name: 'Project Grid', description: 'Portfolio showcase' },
    { key: 'testimonials', name: 'Endorsements', description: 'Client feedback' },
    { key: 'contact', name: 'Inquiry Booking', description: 'Contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
