import { TemplateConfig } from '../types';

export const maisonAtelierConfig: TemplateConfig = {
  id: 'maison-atelier',
  componentKey: 'maison-atelier',
  name: 'Maison Atelier',
  slug: 'maison-atelier',
  aliases: ['template-05-modern'],
  project: 'Project-1 (AI)',
  category: 'creative',
  designStyle: 'Luxury Editorial',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Luxury high-fashion and interior design atelier template with a minimalist alabaster backdrop, magazine spread photography, and gold typography.',
  thumbnailUrl: '/templates/maison-atelier.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Fashion', 'Luxury Atelier', 'Editorial', 'Minimalist', 'Interior'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#C5A059',
    secondaryColor: '#111111',
    accentColor: '#D4AF37',
    backgroundColor: '#FAFAFA',
    textColor: '#111111',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Atelier Hero', description: 'Fashion magazine hero' },
    { key: 'about', name: 'Craftsmanship Story', description: 'Narrative Overview' },
    { key: 'services', name: 'Haute Couture Services', description: 'Atelier offerings' },
    { key: 'gallery', name: 'Editorial Lookbook', description: 'Image showcase' },
    { key: 'testimonials', name: 'Patron Reviews', description: 'Client feedback' },
    { key: 'contact', name: 'Private Appointment', description: 'Booking & contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
