import { TemplateConfig } from '../types';

export const monoArchitectureConfig: TemplateConfig = {
  id: 'mono-architecture',
  componentKey: 'mono-architecture',
  name: 'Mono Architecture',
  slug: 'mono-architecture',
  aliases: ['template-10-modern'],
  project: 'Project-1 (AI)',
  category: 'creative',
  designStyle: 'Minimal Mono',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Minimalist architecture and spatial studio template featuring a monochromatic visual grid system, asymmetric structural layouts, and oversized imagery.',
  thumbnailUrl: '/templates/mono-architecture.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Architecture', 'Monochrome', 'Spatial', 'Minimalist', 'Editorial'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#171717',
    secondaryColor: '#525252',
    accentColor: '#0A0A0A',
    backgroundColor: '#FFFFFF',
    textColor: '#171717',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Monochrome Hero', description: 'Spatial headline' },
    { key: 'about', name: 'Studio Practice', description: 'Architectural ethos' },
    { key: 'services', name: 'Services', description: 'Design & planning' },
    { key: 'gallery', name: 'Built Works', description: 'Project portfolio' },
    { key: 'testimonials', name: 'Client Press', description: 'Endorsements' },
    { key: 'contact', name: 'Project Inquiry', description: 'Studio contact' },
    { key: 'social', name: 'Social Profiles', description: 'Social links' },
  ],
};
