import { TemplateConfig } from '../types';

export const auroraCorporateConfig: TemplateConfig = {
  id: 'aurora-corporate',
  componentKey: 'aurora-corporate',
  name: 'Aurora Corporate',
  slug: 'aurora-corporate',
  aliases: ['template-01', 'project-1:template-01', 'template01'],
  project: 'Project-1 (AI)',
  category: 'consulting',
  designStyle: 'Luxury Editorial',
  responsiveBehavior: 'Fluid Responsive',
  description: 'Executive corporate & advisory template with a spacious split hero, emerald/gold accents, structured governance stats, and elegant typography.',
  thumbnailUrl: '/templates/aurora-corporate.png',
  version: '2.0.0',
  author: 'Emperor Media Solution',
  tags: ['Corporate', 'Executive', 'Advisory', 'Luxury', 'Governance'],
  isFeatured: true,
  defaultTheme: {
    primaryColor: '#075C45',
    secondaryColor: '#C9A45C',
    accentColor: '#D9BD7A',
    backgroundColor: '#FBF8F1',
    textColor: '#1F2937',
    headingFont: 'Cormorant Garamond, serif',
    bodyFont: 'Inter, sans-serif',
  },
  supportedSections: [
    { key: 'theme', name: 'Theme & Fonts', description: 'Brand colors and typography' },
    { key: 'design', name: 'Design & Layout', description: 'Container and button styling' },
    { key: 'seo', name: 'SEO & Metadata', description: 'Search engine optimization' },
    { key: 'hero', name: 'Hero Banner', description: 'Primary headline & CTA' },
    { key: 'about', name: 'About Overview', description: 'Company history & stats' },
    { key: 'services', name: 'Services', description: 'Core practice areas' },
    { key: 'gallery', name: 'Portfolio Gallery', description: 'Case studies & media' },
    { key: 'testimonials', name: 'Client Testimonials', description: 'Client feedback' },
    { key: 'contact', name: 'Contact Details', description: 'Location & communication' },
    { key: 'social', name: 'Social Profiles', description: 'Social media links' },
  ],
};
