export interface TemplateProfile {
  templateKey: string;
  name: string;
  categoryMatches: string[];
  industryKeywords: string[];
  serviceKeywords: string[];
  preferredFeatures: string[];
  excludedKeywords?: string[];
  priority: number;
  dbLookupKeys: string[];
}

export const TEMPLATE_PROFILES: TemplateProfile[] = [
  {
    templateKey: 'ember-hospitality',
    name: 'Ember Hospitality',
    categoryMatches: [
      'restaurant & food',
      'restaurant',
      'food',
      'hospitality',
      'hotel',
      'dining',
      'cafe',
      'catering',
      'bakery',
      'bar',
      'pub',
      'bistro',
      'culinary',
    ],
    industryKeywords: [
      'restaurant',
      'food',
      'dining',
      'cafe',
      'hospitality',
      'hotel',
      'resort',
      'bistro',
      'catering',
      'bakery',
      'bar',
      'pub',
      'chef',
      'cuisine',
      'gourmet',
      'culinary',
      'eatery',
      'lounge',
      'kitchen',
      'dishes',
      'coffee',
      'beverage',
      'gujarati food',
      'indian food',
    ],
    serviceKeywords: [
      'menu',
      'tasting',
      'reservation',
      'dine in',
      'takeaway',
      'delivery',
      'breakfast',
      'lunch',
      'dinner',
      'buffet',
      'cocktail',
      'table booking',
      'food preparation',
      'serving food',
    ],
    preferredFeatures: [
      'Product Catalog / Gallery',
      'Google Map Location',
      'WhatsApp Chat Button',
      'Contact Lead Form',
    ],
    excludedKeywords: ['medical clinic', 'hospital doctor', 'real estate property', 'investment banking'],
    priority: 10,
    dbLookupKeys: ['ember-hospitality', 'template-09', 'project-1-ai-template-09'],
  },
  {
    templateKey: 'vitalis-health',
    name: 'Vitalis Health',
    categoryMatches: [
      'healthcare & medical',
      'healthcare',
      'medical',
      'clinic',
      'hospital',
      'doctor',
      'dental',
      'wellness',
      'pharmacy',
      'care',
    ],
    industryKeywords: [
      'health',
      'medical',
      'clinic',
      'doctor',
      'hospital',
      'dental',
      'dentist',
      'wellness',
      'patient',
      'medicine',
      'healthcare',
      'therapy',
      'pharma',
      'physician',
      'specialist',
      'treatment',
      'orthopedic',
      'cardio',
      'pediatric',
      'nursing',
      'surgery',
      'wellness clinic',
    ],
    serviceKeywords: [
      'appointment',
      'consultation',
      'diagnosis',
      'treatment',
      'therapy',
      'checkup',
      'surgery',
      'dental care',
      'physiotherapy',
      'rehabilitation',
      'prescription',
      'clinical care',
      'wellness',
    ],
    preferredFeatures: [
      'Contact Lead Form',
      'WhatsApp Chat Button',
      'Google Map Location',
    ],
    excludedKeywords: ['restaurant food', 'dining cafe', 'real estate villa', 'fashion boutique'],
    priority: 10,
    dbLookupKeys: ['project-2-template-04', 'vitalis-medical-portal', 'vitalis-health', 'template-04'],
  },
  {
    templateKey: 'framefolio',
    name: 'Framefolio',
    categoryMatches: [
      'portfolio & creative agency',
      'portfolio',
      'photography',
      'photographer',
      'videography',
      'cinematography',
      'visual arts',
      'photo studio',
      'creative media',
    ],
    industryKeywords: [
      'photography',
      'photographer',
      'photo',
      'photos',
      'wedding photography',
      'cinematic',
      'wedding films',
      'wedding',
      'videography',
      'videographer',
      'camera',
      'shoot',
      'portrait',
      'studio photography',
      'visual arts',
      'frames',
      'filmmaking',
      'photoshoot',
      'event photography',
    ],
    serviceKeywords: [
      'wedding shoot',
      'pre wedding',
      'cinematic film',
      'wedding films',
      'portrait session',
      'event coverage',
      'photo editing',
      'album design',
      'video production',
      'commercial photoshoot',
      'photography',
    ],
    preferredFeatures: [
      'Product Catalog / Gallery',
      'Social Media Links',
      'Contact Lead Form',
    ],
    excludedKeywords: ['hospital doctor', 'banking finance', 'real estate developer'],
    priority: 10,
    dbLookupKeys: ['project-2-template-03', 'verve-creative-motion', 'framefolio', 'template-03'],
  },
  {
    templateKey: 'horizon-finance',
    name: 'Horizon Finance',
    categoryMatches: [
      'corporate / business',
      'finance',
      'financial',
      'investment',
      'banking',
      'wealth management',
      'accounting',
      'insurance',
      'tax consulting',
    ],
    industryKeywords: [
      'finance',
      'investment',
      'financial',
      'wealth',
      'capital',
      'banking',
      'asset',
      'audit',
      'tax',
      'insurance',
      'fund',
      'portfolio management',
      'wealth management',
      'fintech',
      'stocks',
      'brokerage',
      'equity',
      'investor',
      'financial consulting',
    ],
    serviceKeywords: [
      'financial consulting',
      'investment advisory',
      'wealth planning',
      'tax filing',
      'portfolio analysis',
      'risk management',
      'retirement planning',
      'fund advisory',
      'audit services',
      'investment and financial',
    ],
    preferredFeatures: [
      'Contact Lead Form',
      'WhatsApp Chat Button',
    ],
    excludedKeywords: ['restaurant food', 'dining culinary', 'fashion boutique', 'photography studio'],
    priority: 10,
    dbLookupKeys: ['project-1-ai-template-04', 'slate-blue-enterprise', 'horizon-finance', 'template-04'],
  },
  {
    templateKey: 'nova-ai',
    name: 'Nova AI',
    categoryMatches: [
      'saas & web application',
      'saas',
      'ai & software',
      'artificial intelligence',
      'machine learning',
      'software company',
      'deep tech',
    ],
    industryKeywords: [
      'ai',
      'artificial intelligence',
      'machine learning',
      'ml',
      'neural',
      'saas',
      'software company',
      'software',
      'algorithm',
      'deep learning',
      'automation',
      'bot',
      'nlp',
      'computer vision',
      'ai platform',
      'cloud software',
      'ai vision',
      'data intelligence',
    ],
    serviceKeywords: [
      'ai models',
      'software development',
      'cloud platform',
      'api integration',
      'predictive analytics',
      'automated workflows',
      'machine learning algorithms',
      'data processing',
    ],
    preferredFeatures: [
      'Contact Lead Form',
      'Blog Section',
      'Social Media Links',
    ],
    excludedKeywords: ['restaurant food', 'dining hotel', 'hospital clinic doctor', 'villas real estate'],
    priority: 10,
    dbLookupKeys: ['project-2-template-01', 'aetheria-tech-cloud', 'nova-ai', 'template-01'],
  },
  {
    templateKey: 'terra-estate',
    name: 'Terra Estate',
    categoryMatches: [
      'architecture & real estate',
      'real estate',
      'property',
      'villas',
      'builders',
      'apartments',
      'housing',
      'realty',
    ],
    industryKeywords: [
      'real estate',
      'property',
      'villa',
      'villas',
      'estate',
      'housing',
      'developer',
      'luxury property',
      'apartment',
      'apartments',
      'lands',
      'plots',
      'realtor',
      'residential',
      'commercial property',
      'property developers',
      'luxury real estate',
      'realty',
      'penthouse',
    ],
    serviceKeywords: [
      'property sales',
      'luxury villas',
      'site visits',
      'apartment leasing',
      'estate development',
      'plot sales',
      'property management',
      'property consulting',
    ],
    preferredFeatures: [
      'Product Catalog / Gallery',
      'Google Map Location',
      'WhatsApp Chat Button',
      'Contact Lead Form',
    ],
    excludedKeywords: ['restaurant dining food', 'medical clinic healthcare', 'clothing fashion boutique'],
    priority: 10,
    dbLookupKeys: ['project-2-template-02', 'apex-luxury-estate', 'terra-estate', 'template-02'],
  },
  {
    templateKey: 'maison-atelier',
    name: 'Maison Atelier',
    categoryMatches: [
      'fashion',
      'clothing',
      'boutique',
      'e-commerce store',
      'luxury apparel',
      'haute couture',
      'jewelry',
      'lifestyle',
    ],
    industryKeywords: [
      'fashion',
      'boutique',
      'designer clothing',
      'luxury designer',
      'haute couture',
      'apparel',
      'clothing brand',
      'couture',
      'atelier',
      'runway',
      'style',
      'tailor',
      'garments',
      'jewelry',
      'luxury fashion',
      'dresses',
      'collection',
      'wear',
    ],
    serviceKeywords: [
      'designer collection',
      'bespoke tailoring',
      'custom couture',
      'fashion styling',
      'apparel catalog',
      'wardrobe consultation',
      'luxury wear',
    ],
    preferredFeatures: [
      'Product Catalog / Gallery',
      'Social Media Links',
      'Contact Lead Form',
    ],
    excludedKeywords: ['hospital medical doctor', 'real estate property', 'heavy engineering', 'banking finance'],
    priority: 10,
    dbLookupKeys: ['project-1-ai-template-05', 'alabaster-minimal', 'maison-atelier', 'template-05'],
  },
  {
    templateKey: 'mono-architecture',
    name: 'Mono Architecture',
    categoryMatches: [
      'architecture & real estate',
      'architecture',
      'architect',
      'interior design',
      'structural engineering',
      'urban planning',
      'construction design',
    ],
    industryKeywords: [
      'architecture',
      'architect',
      'interior design',
      'structural',
      'architectural',
      'blueprint',
      'spatial',
      'urban design',
      'building design',
      'facade',
      'structure',
      'architecture studio',
      'interior decoration',
      'architectural design',
    ],
    serviceKeywords: [
      'architectural planning',
      'interior design',
      '3d visualization',
      'space planning',
      'structural design',
      'landscape architecture',
      'renovation design',
    ],
    preferredFeatures: [
      'Product Catalog / Gallery',
      'Contact Lead Form',
      'Google Map Location',
    ],
    excludedKeywords: ['restaurant food dining', 'medical clinic doctor', 'fashion clothing boutique'],
    priority: 9,
    dbLookupKeys: ['project-1-ai-template-02', 'editorial-terra', 'mono-architecture', 'template-02'],
  },
  {
    templateKey: 'obsidian-studio',
    name: 'Obsidian Studio',
    categoryMatches: [
      'portfolio & creative agency',
      'creative agency',
      'design studio',
      'branding',
      'digital marketing',
      'media agency',
      'advertising',
    ],
    industryKeywords: [
      'creative agency',
      'design studio',
      'branding',
      'brand identity',
      'marketing agency',
      'digital studio',
      'media agency',
      'advertising',
      'graphics',
      'ui ux',
      'creative studio',
      'content studio',
      'art direction',
    ],
    serviceKeywords: [
      'brand strategy',
      'visual identity',
      'ui ux design',
      'digital marketing',
      'campaign design',
      'motion design',
      'content creation',
    ],
    preferredFeatures: [
      'Product Catalog / Gallery',
      'Social Media Links',
      'Contact Lead Form',
    ],
    excludedKeywords: ['medical doctor clinic', 'restaurant food dining', 'photographer wedding photography'],
    priority: 8,
    dbLookupKeys: ['project-1-ai-template-03', 'pitch-gold-studio', 'obsidian-studio', 'template-03'],
  },
  {
    templateKey: 'solaris-tech',
    name: 'Solaris Tech',
    categoryMatches: [
      'technology',
      'cleantech',
      'solar & energy',
      'solar',
      'it solutions',
      'hardware & networking',
      'infrastructure',
      'engineering',
    ],
    industryKeywords: [
      'tech',
      'technology',
      'solar',
      'solar energy',
      'clean energy',
      'renewable energy',
      'hardware',
      'it solutions',
      'telecom',
      'cybersecurity',
      'infrastructure',
      'it services',
      'green tech',
      'engineering systems',
    ],
    serviceKeywords: [
      'solar installation',
      'it consulting',
      'infrastructure management',
      'hardware maintenance',
      'network setup',
      'cloud migration',
      'cybersecurity audit',
    ],
    preferredFeatures: [
      'Contact Lead Form',
      'WhatsApp Chat Button',
      'Blog Section',
    ],
    excludedKeywords: ['restaurant food dining', 'clothing fashion boutique'],
    priority: 8,
    dbLookupKeys: ['project-2-template-05', 'vanguard-corporate-suite', 'solaris-tech', 'template-05'],
  },
  {
    templateKey: 'aurora-corporate',
    name: 'Aurora Corporate',
    categoryMatches: [
      'corporate / business',
      'corporate',
      'business',
      'consulting',
      'management consulting',
      'legal',
      'law firm',
      'advisory',
      'enterprise',
      'other / custom',
    ],
    industryKeywords: [
      'corporate',
      'business',
      'consulting',
      'consultancy',
      'enterprise',
      'legal',
      'law firm',
      'advisory',
      'management',
      'firm',
      'governance',
      'executive',
      'strategy',
      'organization',
      'professional services',
      'global',
    ],
    serviceKeywords: [
      'business advisory',
      'management consulting',
      'strategic planning',
      'corporate governance',
      'legal advisory',
      'risk management',
      'business solutions',
    ],
    preferredFeatures: [
      'Contact Lead Form',
      'WhatsApp Chat Button',
      'Social Media Links',
    ],
    priority: 5,
    dbLookupKeys: ['project-1-ai-template-01', 'emerald-prestige', 'aurora-corporate', 'template-01'],
  },
];
