export interface TemplateDefaultTheme {
  primaryColor: string;
  secondaryColor: string;
  accentColor?: string;
  backgroundColor: string;
  textColor: string;
  headingFont: string;
  bodyFont: string;
  heroLayout?: string;
  aboutLayout?: string;
  servicesStyle?: string;
  galleryStyle?: string;
  testimonialsStyle?: string;
  contactStyle?: string;
  sectionSpacing?: string;
  containerWidth?: string;
  buttonSize?: string;
  designPreset?: string;
}

export const TEMPLATE_DEFAULT_THEMES: Record<string, TemplateDefaultTheme> = {
  'aurora-corporate': {
    primaryColor: '#075C45',
    secondaryColor: '#C9A45C',
    accentColor: '#D9BD7A',
    backgroundColor: '#FBF8F1',
    textColor: '#1F2937',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Executive Advisory',
  },
  'obsidian-studio': {
    primaryColor: '#E5B842',
    secondaryColor: '#FFFFFF',
    accentColor: '#A855F7',
    backgroundColor: '#0A0A0C',
    textColor: '#FFFFFF',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'centered',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'luxury',
    containerWidth: 'standard',
    buttonSize: 'medium',
    designPreset: 'Creative Studio',
  },
  'terra-estate': {
    primaryColor: '#B85B35',
    secondaryColor: '#231B18',
    accentColor: '#D97706',
    backgroundColor: '#F5EFE6',
    textColor: '#231B18',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Luxury Real Estate',
  },
  'nova-ai': {
    primaryColor: '#4F46E5',
    secondaryColor: '#06B6D4',
    accentColor: '#8B5CF6',
    backgroundColor: '#090D16',
    textColor: '#F8FAFC',
    headingFont: 'Plus Jakarta Sans, sans-serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Deep Tech SaaS',
  },
  'maison-atelier': {
    primaryColor: '#1A1A1A',
    secondaryColor: '#D4AF37',
    accentColor: '#8C7B68',
    backgroundColor: '#FAF8F5',
    textColor: '#1A1A1A',
    headingFont: 'Cormorant Garamond, serif',
    bodyFont: 'Montserrat, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'standard',
    buttonSize: 'medium',
    designPreset: 'Haute Couture',
  },
  'vitalis-health': {
    primaryColor: '#0284C7',
    secondaryColor: '#0D9488',
    accentColor: '#38BDF8',
    backgroundColor: '#F0F9FF',
    textColor: '#0F172A',
    headingFont: 'Plus Jakarta Sans, sans-serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Clinical Wellness',
  },
  'horizon-finance': {
    primaryColor: '#1E3A8A',
    secondaryColor: '#D97706',
    accentColor: '#3B82F6',
    backgroundColor: '#F8FAFC',
    textColor: '#0F172A',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Wealth Advisory',
  },
  'framefolio': {
    primaryColor: '#D97706',
    secondaryColor: '#FFFFFF',
    accentColor: '#F59E0B',
    backgroundColor: '#0F0F11',
    textColor: '#F3F4F6',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'luxury',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Visual Showcase',
  },
  'ember-hospitality': {
    primaryColor: '#991B1B',
    secondaryColor: '#D97706',
    accentColor: '#F59E0B',
    backgroundColor: '#0F0F12',
    textColor: '#F5F5F4',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Culinary Hospitality',
  },
  'mono-architecture': {
    primaryColor: '#171717',
    secondaryColor: '#737373',
    accentColor: '#A3A3A3',
    backgroundColor: '#FAFAFA',
    textColor: '#171717',
    headingFont: 'Space Grotesk, sans-serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'Architectural Purity',
  },
  'solaris-tech': {
    primaryColor: '#059669',
    secondaryColor: '#F59E0B',
    accentColor: '#10B981',
    backgroundColor: '#061A14',
    textColor: '#ECFDF5',
    headingFont: 'Plus Jakarta Sans, sans-serif',
    bodyFont: 'Inter, sans-serif',
    heroLayout: 'split',
    aboutLayout: 'text-image',
    servicesStyle: 'cards',
    galleryStyle: 'grid',
    testimonialsStyle: 'cards',
    contactStyle: 'split',
    sectionSpacing: 'spacious',
    containerWidth: 'wide',
    buttonSize: 'medium',
    designPreset: 'CleanTech Solar',
  },
};
